{
 "title": "Erigon (Ethereum Sepolia Node)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "quantile",
    "query": "0.0,0.25,0.5, 0.9, 0.97, 0.99, 1"
   },
   { "name": "instance", "label": "instance", "query": { "query": "go_goroutines" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Erigon Version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "erigon_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Chain head",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\",stage=\"headers\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block: {{instance}}"
    }
   ]
  },
  {
   "title": "Sync Stages progress",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\"}",
     "legendFormat": "{{ stage }}: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    }
   ]
  },
  {
   "title": "RPC (remote procedure call)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "description": "Request Per Second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"success\"}[1m])",
       "legendFormat": "success {{ method }} {{ instance }} "
      },
      {
       "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"failure\"}[1m])",
       "legendFormat": "failure {{ method }} {{ instance }} "
      }
     ]
    },
    {
     "title": "Timings",
     "type": "timeseries",
     "description": "Timing for sync synchronization",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rpc_duration_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": " {{ method }} {{ instance }} {{ success }}"
      }
     ]
    },
    {
     "title": "Average Request per 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "rate(rpc_total{instance=\"erigon:6061\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GO Goroutines and Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{instance=~\"$instance\"}",
       "legendFormat": "go/goroutines: {{instance}}"
      },
      {
       "expr": "go_threads{instance=~\"$instance\"}",
       "legendFormat": "go/threads: {{instance}}"
      }
     ]
    },
    {
     "title": "Data Base",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(pool_write_to_db_bytes{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "pool_write_to_db_bytes: {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "MemPool Ethereum Sepolia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "description": "Request Per Second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(pool_process_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "pool_process_remote_txs_count: {{ instance }}"
      },
      {
       "expr": "rate(pool_add_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "pool_add_remote_txs_count: {{ instance }}"
      },
      {
       "expr": "rate(pool_new_block_count{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "pool_new_block_count: {{ instance }}"
      },
      {
       "expr": "rate(pool_write_to_db_count{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "pool_write_to_db_count: {{ instance }}"
      },
      {
       "expr": "rate(pool_p2p_out{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timings",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "pool_process_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "process_remote_txs: {{ instance }}"
      },
      {
       "expr": "pool_add_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "add_remote_txs: {{ instance }}"
      },
      {
       "expr": "pool_new_block{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "new_block: {{ instance }}"
      },
      {
       "expr": "pool_write_to_db{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "write_to_db: {{ instance }}"
      },
      {
       "expr": "pool_propagate_to_new_peer{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "propagate_to_new_peer: {{ instance }}"
      },
      {
       "expr": "pool_propagate_new_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "propagate_new_txs: {{ instance }}"
      }
     ]
    },
    {
     "title": "Transaction pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "txpool_pending{instance=~\"$instance\"}",
       "legendFormat": "executable: {{instance}}"
      },
      {
       "expr": "txpool_basefee{instance=~\"$instance\"}",
       "legendFormat": "basefee: {{instance}}"
      },
      {
       "expr": "txpool_queued{instance=~\"$instance\"}",
       "legendFormat": "gapped: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caplin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Caplin: Total bandwidth",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(rate(total_out_bytes{instance=~\"$instance\"}[$__rate_interval])+rate(total_in_bytes{instance=~\"$instance\"}[$__rate_interval])+(rate(gossip_topics_seen_beacon_aggregate_and_proof{instance=~\"$instance\"}[$__rate_interval])*15)) > 0\n",
       "legendFormat": "kb/s {{instance}}"
      }
     ]
    },
    {
     "title": "Caplin: Attestation in block latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "attestation_block_processing_time{instance=~\"$instance\"}",
       "legendFormat": " {{ method }} {{ instance }}"
      }
     ]
    },
    {
     "title": "Shuffling validator set",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "compute_shuffled_indices{instance=~\"$instance\"} > 0",
       "legendFormat": "{{label_name}} {{instance}}"
      }
     ]
    },
    {
     "title": "Intra-epoch processing time",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "process_justification_bits_and_finality_time{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}} process_justification_bits_and_finality"
      },
      {
       "expr": "process_inactivity_ccores_time{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}} process_inactivity_scores"
      },
      {
       "expr": "process_rewards_and_penalties_time{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}} process_rewards_and_penalties_time"
      },
      {
       "expr": "process_registry_updates_time{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}} process_registry_updates_time"
      },
      {
       "expr": "process_slashings_time{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}} process_slashings_time"
      },
      {
       "expr": "process_historical_roots_update_time{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}} process_historical_roots_update_time"
      },
      {
       "expr": "process_sync_committee_update_time{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}} process_sync_committee_update_time"
      }
     ]
    },
    {
     "title": "ValidateChain: time spent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "execution_time{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}}"
      }
     ]
    },
    {
     "title": "Caplin: Ingoing bandwidth",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(rate(total_in_bytes{instance=~\"$instance\"}[$__rate_interval])) > 0\n",
       "legendFormat": "kb/s {{instance}}"
      }
     ]
    },
    {
     "title": "Block importing latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "block_importing_latency{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}}"
      }
     ]
    },
    {
     "title": "Beacon Block Gossip bandwidth",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(gossip_topics_seen_beacon_block{instance=~\"$instance\"}[$__rate_interval])/125 > 0  ",
       "legendFormat": "kb/s {{instance}}"
      }
     ]
    },
    {
     "title": "Caplin: Outgoing bandwidth",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(rate(total_out_bytes{instance=~\"$instance\"}[$__rate_interval])) > 0\n",
       "legendFormat": "kb/s {{instance}}"
      }
     ]
    },
    {
     "title": "Total blobs bandwidth",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(rate(gossip_topics_seen_blob_sidecar_0{instance=~\"$instance\"}[$__rate_interval])+rate(gossip_topics_seen_blob_sidecar_1{instance=~\"$instance\"}[$__rate_interval])+rate(gossip_topics_seen_blob_sidecar_2{instance=~\"$instance\"}[$__rate_interval])+rate(gossip_topics_seen_blob_sidecar_3{instance=~\"$instance\"}[$__rate_interval])+rate(gossip_topics_seen_blob_sidecar_4{instance=~\"$instance\"}[$__rate_interval])+rate(gossip_topics_seen_blob_sidecar_5{instance=~\"$instance\"}[$__rate_interval]))/125  > 0",
       "legendFormat": "kb/s {{instance}}"
      }
     ]
    },
    {
     "title": "Total SyncCommitteeAggregate bandwidth",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(rate(gossip_topics_seen_sync_committee_contribution_and_proof{instance=~\"$instance\"}[$__rate_interval]))/125  > 0\n",
       "legendFormat": "kb/s {{instance}}"
      }
     ]
    },
    {
     "title": "Total AggregateAndProof bandwidth",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(rate(gossip_topics_seen_beacon_aggregate_and_proof{instance=~\"$instance\"}[$__rate_interval]))/125  > 0",
       "legendFormat": "kb/s {{instance}}"
      }
     ]
    },
    {
     "title": "Blob sidecar computation time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "blob_verification_time{instance=~\"$instance\"}",
       "legendFormat": "{{label_name}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Beacon Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attestating Committee Size",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 434 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "committee_size{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current epoch",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 434 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "current_epoch{instance=~\"$instance\"}",
       "legendFormat": "Epoch {{instance}}"
      }
     ]
    },
    {
     "title": "Current slot",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 434 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "current_slot{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Stages progress",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 535 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sync{instance=~\"$instance\",stage=\"execution\"} > 0 ",
       "legendFormat": "{{ stage }}: {{instance}}"
      }
     ]
    },
    {
     "title": "Exec v3: txs/s ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 535 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(exec_txs_done{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "txs apply:  {{instance}}"
      },
      {
       "expr": "irate(exec_txns{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "txn/s {{instance}}"
      },
      {
       "expr": "rate(exec_txs_done{instance=~\"$instance\"}[$rate_interval]) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Execution speed ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 535 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "chain_execution_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
       "legendFormat": "execution: {{instance}}"
      }
     ]
    },
    {
     "title": "Block execution delays",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 540 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "block_consumer_delay{type=\"header_download\",instance=~\"$instance\",quantile=\"$quantile\"}",
       "legendFormat": "header: {{instance}}"
      },
      {
       "expr": "block_consumer_delay{type=\"body_download\",instance=~\"$instance\",quantile=\"$quantile\"}",
       "legendFormat": "body: {{instance}}"
      },
      {
       "expr": "block_consumer_delay{type=\"pre_execution\",instance=~\"$instance\",quantile=\"$quantile\"}",
       "legendFormat": "execution_start: {{instance}}"
      },
      {
       "expr": "block_consumer_delay{type=\"post_execution\",instance=~\"$instance\",quantile=\"$quantile\"}",
       "legendFormat": "execution_end: {{instance}}"
      }
     ]
    },
    {
     "title": "Sync Stages progress rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 541 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(sync{instance=~\"$instance\",stage=\"execution\"}[$rate_interval]) ",
       "legendFormat": "{{ stage }}:  {{instance}}"
      }
     ]
    },
    {
     "title": "State: Collate/Prune/Merge/Commitment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 546 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(domain_collation_size{instance=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "collated [domain]: {{instance}}"
      },
      {
       "expr": "irate(domain_collation_hist_size{instance=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "collated [history]: {{instance}}"
      },
      {
       "expr": "sum(rate(domain_commitment_keys{instance=~\"$instance\"}[$__rate_interval])) by (instance) > 0",
       "legendFormat": "keys committed: {{instance}}"
      },
      {
       "expr": "irate(domain_commitment_updates{instance=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "commitment node updates: {{instance}}"
      },
      {
       "expr": "irate(domain_commitment_updates_applied{instance=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "commitment trie node updates: {{instance}}"
      },
      {
       "expr": "irate(domain_prune_size{instance=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "pruned keys [{{type}}]: {{instance}}"
      }
     ]
    },
    {
     "title": "mgas/s ",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 546 },
     "fieldConfig": { "defaults": { "unit": "mgas/sec" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "exec_mgas{instance=~\"$instance\"} < 5000",
       "legendFormat": "mgas:  {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commit",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 436 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(db_commit_seconds_count{phase=\"total\",instance=~\"$instance\"}[$rate_interval]) > 0 ",
       "legendFormat": "commit: {{instance}}"
      }
     ]
    },
    {
     "title": "Commit speed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 436 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "db_commit_seconds{phase=\"total\",quantile=\"$quantile\",instance=~\"$instance\"} > 0",
       "legendFormat": "total: {{instance}}"
      },
      {
       "expr": "db_commit_seconds{phase=\"gc_wall_clock\",quantile=\"$quantile\",instance=~\"$instance\"} > 0",
       "legendFormat": "gc_wall_clock: {{instance}}"
      },
      {
       "expr": "db_commit_seconds{phase=\"write\",quantile=\"$quantile\",instance=~\"$instance\"} > 0",
       "legendFormat": "write: {{instance}}"
      },
      {
       "expr": "db_commit_seconds{phase=\"sync\",quantile=\"$quantile\",instance=~\"$instance\"} > 0.002",
       "legendFormat": "sync: {{instance}}"
      },
      {
       "expr": "db_commit_seconds{phase=\"gc_cpu_time\",quantile=\"$quantile\",instance=~\"$instance\"} > 0",
       "legendFormat": "gc_cpu_time: {{instance}}"
      }
     ]
    },
    {
     "title": "DB Size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 473 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "db_size{instance=~\"$instance\"}",
       "legendFormat": "size: {{instance}}"
      },
      {
       "expr": "db_mi_last_pgno{instance=~\"$instance\"}",
       "legendFormat": "db_mi_last_pgno: {{instance}}"
      }
     ]
    },
    {
     "title": "Tx Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 478 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "tx_limit{instance=~\"$instance\"}",
       "legendFormat": "limit: {{instance}}"
      },
      {
       "expr": "tx_dirty{instance=~\"$instance\"}",
       "legendFormat": "dirty: {{instance}}"
      }
     ]
    },
    {
     "title": "DB Pages Ops/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 478 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(db_pgops{phase=\"newly\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "newly: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"cow\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "cow: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"clone\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "clone: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"split\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "split: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"merge\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "merge: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"spill\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "spill: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"wops\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "wops: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"unspill\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "unspill: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"gcrloops\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "gcrloops: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"gcwloops\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "gcwloops: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"gcxpages\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "gcxpages: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"msync\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "msync: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"fsync\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "fsync: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"minicore\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "minicore: {{instance}}"
      },
      {
       "expr": "rate(db_pgops{phase=\"prefault\", instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "prefault: {{instance}}"
      }
     ]
    },
    {
     "title": "GC and State",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 484 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "db_gc_leaf{instance=~\"$instance\"} > 0",
       "legendFormat": "gc_leaf: {{instance}}"
      },
      {
       "expr": "db_gc_overflow{instance=~\"$instance\"} > 0",
       "legendFormat": "gc_overflow: {{instance}}"
      },
      {
       "expr": "exec_steps_in_db{instance=~\"$instance\"}/100 > 0",
       "legendFormat": "exec_steps_in_db: {{instance}}"
      }
     ]
    },
    {
     "title": "getrusage: minflt - soft page faults (reclaims), majflt - hard faults",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 484 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(process_minor_pagefaults_total{instance=~\"$instance\"}[$rate_interval]) > 0",
       "legendFormat": "soft: {{instance}}"
      },
      {
       "expr": "rate(process_major_pagefaults_total{instance=~\"$instance\"}[$rate_interval]) > 0",
       "legendFormat": "hard: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "mem: resident set size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "resident mem: {{instance}}"
      },
      {
       "expr": "mem_data{instance=~\"$instance\"}",
       "legendFormat": "data: {{instance}}"
      },
      {
       "expr": "mem_stack{instance=~\"$instance\"}",
       "legendFormat": "stack: {{instance}}"
      },
      {
       "expr": "mem_locked{instance=~\"$instance\"}",
       "legendFormat": "locked: {{instance}}"
      },
      {
       "expr": "mem_swap{instance=~\"$instance\"}",
       "legendFormat": "swap: {{instance}}"
      }
     ]
    },
    {
     "title": "Read/Write syscall/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(process_io_write_syscalls_total{instance=~\"$instance\"}[$rate_interval]) > 0",
       "legendFormat": "in: {{instance}}"
      },
      {
       "expr": "rate(process_io_read_syscalls_total{instance=~\"$instance\"}[$rate_interval]) > 0",
       "legendFormat": "out: {{instance}}"
      }
     ]
    },
    {
     "title": "cgo calls",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(go_cgo_calls_count{instance=~\"$instance\"}[$rate_interval]) > 0",
       "legendFormat": "cgo_calls_count: {{instance}}"
      }
     ]
    },
    {
     "title": "Disk bytes/sec",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(process_io_storage_read_bytes_total{instance=~\"$instance\"}[$rate_interval]) > 0",
       "legendFormat": "read: {{instance}}"
      },
      {
       "expr": "rate(process_io_storage_written_bytes_total{instance=~\"$instance\"}[$rate_interval]) > 0",
       "legendFormat": "write: {{instance}}"
      }
     ]
    },
    {
     "title": "Process Mem: allocate objects/sec, free",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 457 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "memstats_mallocs_total: {{ instance }}"
      },
      {
       "expr": "rate(go_memstats_frees_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "memstats_frees_total: {{ instance }}"
      }
     ]
    },
    {
     "title": "go memstat",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 457 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
       "legendFormat": "stack_sys: {{ instance }}"
      },
      {
       "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
       "legendFormat": "sys: {{ instance }}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "stack_inuse: {{ instance }}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
       "legendFormat": "mspan_sys: {{ instance }}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
       "legendFormat": "mcache_sys: {{ instance }}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
       "legendFormat": "heap_alloc: {{ instance }}"
      }
     ]
    },
    {
     "title": "GO Goroutines and Threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 457 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{instance=~\"$instance\"}",
       "legendFormat": "goroutines: {{instance}}"
      },
      {
       "expr": "go_threads{instance=~\"$instance\"}",
       "legendFormat": "threads: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 463 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "increase(process_cpu_seconds_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "system: {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Use",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 463 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
       "legendFormat": "current: {{ instance }}"
      }
     ]
    },
    {
     "title": "GC Stop the World per sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 463 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds{quantile=\"0.75\",instance=~\"$instance\"}[$rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(p2p_ingress{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "ingress: {{instance}}"
      },
      {
       "expr": "rate(p2p_egress{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "egress: {{instance}}"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "p2p_peers{instance=~\"$instance\"}",
       "legendFormat": "peers: {{instance}}"
      },
      {
       "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
       "legendFormat": "dials: {{instance}}"
      },
      {
       "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
       "legendFormat": "serves: {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Erigon Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Erigon Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{container=\"erigon\"} |= ``"
    }
   ]
  }
 ]
}